## NumPy is a python librabry used to work with arrays
## NumPy stands for Numerical Python
## Was created by Travis Oliphant in 2005

## --------------------------------------------------------------

## We can use lists in python to work with arrays, but lists are slow.
## NumPy is 50X faster than lists in python.
## Arrays are used in Data Science, where speed and resourses are very important/
## Numpy Arrays are stored in one continous place in memory unlike lists. So processing is quick.
## This behaviour is called locality of reference in computer science
## This is the main reason why NumPy is faster than lists.
## Numpy is partially written in pytho, but  most of the parts that require fast computations are written in c or c++

## ----------------------------------------------------------

## Installing NumPy

In [3]:
! pip install NumPy   # this line will install NumPy from the internet. By default, its installed in Jupyter Notebook

## Importing NumPy as np

In [5]:
import numpy as np   # Now we can write np instead of writing NumPy everytime

## Checking version of numpy

In [6]:
np.__version__    # __version__ underscore is twice

'1.20.3'

## Creating numpy Arrays

## we can create arrays using the array() fuction


In [7]:
# Example of creating array using list

import numpy as np

new_list = np.array([10,12,16,17,9])    # arrays are created using array() function
print(new_list)   # list of arrays is printed

[10 12 16 17  9]


In [8]:
type(new_list)   # type of new_list is checked. Output is ndarray

numpy.ndarray

In [9]:
## using a tuple to create arrays
import numpy as np

new_list2 = np.array((2,3,5,7,9))    # creating array using tuple

print(new_list2)   # printing the new_list2

[2 3 5 7 9]


In [10]:
# checking the type of the new_list2. ndarray is the output. ndarray means n dimensional array
type(new_list2)

numpy.ndarray

## Dimensions in Arrays

In [13]:
## Example of 0 dimensional array
array1 = np.array(23)   # if there is only element, its 0 dimensional array

print(array1)   

# checking the dimensions of an array.To do that we use, ndim attribute
array1.ndim   # 0 is printed, as array1 is a 0 dimensional array


23


0

In [21]:
# Example of 1 dimensional array 

array2 = np.array([12,14,15,20]) 

print(array2)  ## prints the array

print(type(array2))  ## prints the type of array
 
print(array2.ndim)   ## prints dimensions of array

[12 14 15 20]
<class 'numpy.ndarray'>
1


In [24]:
#Example of 2 dimensional array

# An array that has 1-d array as an element is called as 2d array(matrices)

array3 = np.array([[1,3,4], [5,8,9]])

print(array3)

print(array3.ndim)   # prints 2 as its a 2d array

[[1 3 4]
 [5 8 9]]
2


In [28]:
# example of 3-d arrays

# An array that has 2-dimensinal array as an element.

array4 = np.array([[[2,3,5], [7,8,6]],[[1,2,3],[5,6,4]]])

print(array4)
print()
print(array4.ndim)    # prints 3 as its a 3-d array

[[[2 3 5]
  [7 8 6]]

 [[1 2 3]
  [5 6 4]]]

3


In [33]:
# Higher dimensional arrays

# we can create higher dimensional arrays just by defining ndmin argument when arrays are created

array5 = np.array([2,5,7,4,8], ndmin=5)   # creates a 5-d array
print(array5)
print()
print(array5.ndim)   # prints 5 as its a 5-d array

[[[[[2 5 7 4 8]]]]]

5


## Indexing Arrays or Acessing Arrays

In [34]:
# Indexing array pr Array indexing is same as acessing an array element.
# We can access to an array element using index number
# indexes start from 0 which means 1st element has index 0

import numpy as np

array6 = np.array([4,6,7,10])

print(array6[2])   # 7 will be printed, as its index is 2

7


In [36]:
# We can perform operations on the elemets using the indexes

array7 = np.array([9,6,5,4])

x = array7[3] + array7[1]   # 4+6
print(x)

10


## Acessing 2-D Arrays

In [44]:
# Imagine 2-d arrays like table of rows and columns

array8 = np.array([[1,2,3,4,5],[9,8,7,5,6]])

print(array8)  # prints it like a table. Rows start with 0 and columns start with 0.
               # If we want to get 4, we need to write [0,3] row 0 and column 3rd
    
print(array8[0,3])  # prints 4

[[1 2 3 4 5]
 [9 8 7 5 6]]
4


## Accessing 3-D Arrays

In [47]:
array9 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(array9[0,1,2])

# the above print statment prints 6
# we have 3-d array as 
# [[1,2,3],[4,5,6]]
# [[7,8,9],[10,11,12]]
# we selected 0, that means we are left with [[1,2,3],[4,5,6]]
# we slected 1, that means we are left with [4,5,6]
# we slected 2 that means we are left with 6


6


## Accessing with negative indexes 

In [50]:
# We use negative indexes to access elements from the left

array10 = np.array([[1,2,3,4],[6,7,8,9]])

x=array10[1,-1]  #x is now 9. Since we selected 1, we are left with [6,7,8,9]. we selected -1 i.e. 9
print(x)

9


## ---------------------------------------------------------------
## Array Slicing

In [54]:
# example of slicing an array
# syntax is [start:end] or [start:end:step]

array11 = np.array([2,4,6,3,7,8,19,23,54,23,19,45,67,89])

print(array11[1:4])  # from index[1] to index[3] 
                    # note: the result includes start  index but excludes the end index

[4 6 3]


In [58]:
print(array11[2:8:2])   # [start:end:step] start is starting index, end is 1 less, step is skip by 2 

[ 6  7 19]


In [59]:
print(array11[2:])   #from index 2 to end of the array

[ 6  3  7  8 19 23 54 23 19 45 67 89]


In [60]:
print(array11[:5])  #from begining to the index[5] not included

[2 4 6 3 7]


## We can slice using negative indexes also

## --------------------------------------------------------------------------------

## Getting the shape of an array

In [67]:
# We have shape attribute that gives the output as tuple

arr1 = np.array([[1,2,3,4], [5,6,7,8]])

print(arr1)
print()
print(arr1.shape)    # gives the spahe of the array.. 2 rows, 4 coulmns

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


## ------------------------------------------------------------

## Reshaping arrays...... from 1d to 2d or 3d etc

In [69]:
#converting 1d array with 12 elements into 2d array

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_arr2 = arr2.reshape(3,4)   # new array will have 3 arrays with 4 elements each

new_arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
#Converting 1d to 3d 

arr3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_arr3=arr3.reshape(3,2,2)  # 3dimensions, 2 arrays, each array will have 2 elements

new_arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## ------------------------------------------------------------------------

## Iterating Arrays

In [76]:
# Iterating means going through the elements one by one
# we can do iteration using for loop
# iterating 1d array

arr3 = np.array([4,5,6,7,8])

for x in arr3:
    print(x)

4
5
6
7
8


In [79]:
#iterating 2d array

arr4 = np.array([[1,2,3,4],[5,6,7,8]])  
for x in arr4:
    print(x)    # prints the rows

[1 2 3 4]
[5 6 7 8]


## ----------------------------------------------------

## Joining Arrays

In [81]:
# Joining means putting contents of two or more arrays in a single array

x1 = np.array([1,2,3,4]) 
x2 = np.array([5,6,7,8])

new_array = np.concatenate((x1,x2))  # new array is [1,2,3,4,5,6,7,8]
print(new_array)


[1 2 3 4 5 6 7 8]


In [90]:
y1 = np.array([[1,2],[4,5]])
y2 = np.array([[7,8],[9,1]])

new_array2 = np.concatenate((y1, y2), axis=1)
print(new_array2)

[[1 2 7 8]
 [4 5 9 1]]
